# Support Python 3.10+.
target-version = "py310"
# Set the maximum line length to 80.
line-length = 80

[lint]
# A configuration that enables some of the most popular rules (without being too pedantic) might look like the following:
select = [
    # flake8
    "E",    # pycodestyle
    "F",    # Pyflakes
    "C",    # mccabe
    # flake8 option
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify

    "UP",   # pyupgrade
    "I",    # isort
    "W",    # pycodestyle warnings
]
extend-select = [
    "E501",    # Add the `line-too-long` rule to the enforced rule set.
    "UP",  # pyupgrade
    "D",   # pydocstyle
]
# Cases where pre-commit doesn't fix the problem
unfixable = ["F401", "F841"]

[lint.pydocstyle]
convention = "google"
