# Support Python 3.10+.
target-version = "py310"

# Set the maximum line length to 80.
line-length = 80

exclude = [
    "__pycache__",
]

[lint]
# A configuration that enables some of the most popular rules (without being too pedantic) might look like the following:
select = [
    # flake8
    "E",    # pycodestyle
    "F",    # Pyflakes
    "C",    # mccabe

    "UP",   # pyupgrade
    "I",    # isort
    "W",    # pycodestyle warnings
]
extend-select = [
    "UP",  # pyupgrade
]
#    "D",   # pydocstyle

# Cases where pre-commit doesn't fix the problem
unfixable = ["F401", "F841", "D101"]

[lint.pydocstyle]
convention = "google"

